### ISSUE TITLE
IAM - Consent Page does not redirect back to Sample after consent is given

### ISSUE THREAD

**Issue by tarasklimenko** [attdevsupport/ATT_APIPlatform_PhoneGap#33]
#### Description:

In the Phonegap SDK IAM Sample App, the user is blocked on the consent screen. After providing consent, and count-down goes to zero, the user is not redirected back to the IAM Sample App. Instead, is stuck on the consent-confirmation page. 

#### Actual:
User is not redirected back to IAM Sample from the User-Consent page

#### Expected:
User to be redirected to the IAM Sample as soon as the Consent is given 

#### Repro Steps:
1) Launch Phonegap 2.0 IAM Sample App
2) Populate "Mobile Number" field and tap "Login"
3) Tap "Allow" to give consent 
4) Notice "Thank you! Permission Granted" Page is shown
5) Notice "You will be redirected back to"  at bottom with count down
6) Notice once countdown goes to zero, nothing happens. User is not redirected to IAM Sample App

**Comment by mattcobb** [comment]
Changed this from iFrame to native browser plugin so x-site scripting is not an issue.
